# Generated by Django 4.1.3 on 2022-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('player', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='hosting',
            field=models.BooleanField(blank=True),
        ),
    ]
